import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import type { LanguageModelUsage } from 'ai'
import type { ChangeSet } from './changes'
import type { SpecOutcome } from './verify'

export interface AgentReport {
  pr?: number
  model: string
  changes: Pick<ChangeSet, 'base' | 'head' | 'routes' | 'endpoints' | 'sharedUi'>
  skippedReason?: string
  steps?: number
  usage?: LanguageModelUsage
  outcomes: SpecOutcome[]
  notes?: string
}

const fence = (lang: string, body: string) => `\`\`\`${lang}\n${body.trimEnd()}\n\`\`\``

export function renderMarkdown(r: AgentReport): string {
  const added = r.outcomes.filter((o) => o.status === 'added')
  const bugs = r.outcomes.filter((o) => o.status === 'suspected_app_bug')
  const dropped = r.outcomes.filter((o) => o.status === 'not_added')
  const scope = [...r.changes.routes, ...r.changes.endpoints, ...r.changes.sharedUi].map((s) => `\`${s}\``).join(', ')
  const tokens = r.usage ? ` · ${r.usage.inputTokens ?? '?'} in / ${r.usage.outputTokens ?? '?'} out tokens` : ''

  const lines = [
    `## E2E agent: generated tests${r.pr ? ` for #${r.pr}` : ''}`,
    '',
    `Changes \`${r.changes.base.slice(0, 7)}...${r.changes.head.slice(0, 7)}\` · scope: ${scope || '—'}`,
    `Model \`${r.model}\`${r.steps ? ` · ${r.steps} steps` : ''}${tokens}`,
    '',
  ]

  if (r.skippedReason) return [...lines, r.skippedReason, ''].join('\n')

  lines.push('### Added', '')
  if (added.length) {
    lines.push('Each spec below passed twice in a row against the PR branch.', '')
    for (const o of added) lines.push(`- \`${o.path}\` — ${o.tests} test${o.tests === 1 ? '' : 's'}${o.summary ? `: ${o.summary}` : ''}`)
  } else {
    lines.push('No spec passed verification, so nothing was added.')
  }
  lines.push('')

  if (bugs.length) {
    lines.push('### Suspected app bugs', '', 'The agent believes these tests are correct and the app is wrong. They are not committed.', '')
    for (const o of bugs) {
      lines.push(`<details><summary><code>${o.name}</code> — ${o.summary || 'no summary'}</summary>`, '')
      lines.push(fence('text', o.error ?? ''), '', fence('ts', o.content ?? ''), '', '</details>', '')
    }
  }

  if (dropped.length) {
    lines.push('### Not added', '')
    for (const o of dropped) {
      lines.push(`<details><summary><code>${o.name}</code> — agent said <code>${o.agentStatus ?? 'nothing'}</code>, failed verification</summary>`, '')
      lines.push(fence('text', o.error ?? ''), '', '</details>', '')
    }
  }

  if (r.notes) lines.push('### Notes from the agent', '', r.notes, '')
  lines.push('---', '_Generated by an AI agent (`tools/e2e-agent`). Review the tests like any other code before merging._', '')
  return lines.join('\n')
}

export function writeReport(outDir: string, report: AgentReport) {
  mkdirSync(outDir, { recursive: true })
  writeFileSync(path.join(outDir, 'report.json'), JSON.stringify(report, null, 2))
  writeFileSync(path.join(outDir, 'report.md'), renderMarkdown(report))
}
